---
- hosts: t-server
  tasks:
    # - debug: var=inventory_hostname
    # - debug: var=ansible_hostname
    - debug:
        var: ansible_facts.env
    - debug:
        var: ansible_facts.python
    - debug:
        msg:
          - "hello world."
    # - assert:
    #     that:
    #       - "'foo' in 'some_command_result.stdout,foo'"
    #       - ansible_facts.python.executable == '/usr/bin/python3'
    #     fail_msg: "{{ansible_facts.python.executable}} is wrong"
    #     quiet: yes
    #     success_msg: "'my_param' is between 0 and 100"
    - name: install git and python3-virtualenv
      apt:
        pkg:
          - git
          - python3-virtualenv

    # - debug: var=hostvars
