---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  vars_files:
    - config.cfg
    - config-mine.cfg
  vars:
    users: ["1"]
  
  tasks:
    - debug:
        var: users

