- name: Get data from Github
  uri:
    url: "{{ gl_endpoint }}"
    method: POST
    headers:
      x-hasura-admin-secret: "{{ hasura_admin }}"
    body_format: json
    body:
      query: |
        query GetRemainCfgUsers {
            wireguard_cfg(where: {server: {ipv4: {_eq: "{{ vpn_server_ip }}"}}, _and: {state: {_in: [normal, preparing]}}}) {
            id
            uuid
          }
        }
  register: server_result
- name: set fact value.
  set_fact:
    users_with_uuid: ""
    users: "{{ server_result.json.data.wireguard_cfg | map(attribute='id') | map('regex_replace', '^(.*)$', 'user\\1') | list }}"
- name: print result.
  debug:
    var: users
- name: read old user list
  include_vars:
    file: ../cfg_users_list.json
    name: old_users_list
- name: print out old user list.
  debug:
    var: old_users_list
# - name: save diff users
#   copy:
#     content: "{{ {'users_list_new': users_list | difference(old_users_list.users)} }}"
#     dest: ../cfg_users_list_new.json
- name: write new users_list
  copy:
    content: "{{ {'users': users} }}"
    dest: ../cfg_users_list.json

  

# https://yaml-multiline.info/