- name: insert server.
  uri:
    url: "{{ gl_endpoint }}"
    method: POST
    headers:
      x-hasura-admin-secret: "{{ hasura_admin }}"
    body_format: json
    body:
      query: |
        mutation CreateServer {
          insert_server_one(object: {ipv4: "{{ vpn_server_ip }}", max_conf: {{ max_conf | default(250)}}, provider: {{ provider | default("hetzner") }}, continent: "{{ continent | default("EUROPE")}}" }) {
            id
            created_at
            ipv4
            provider
            region
            max_conf
          }
        }
  register: server_create_result
  # ignore_errors: true
- name: print server create result.
  debug:
    msg: "{{ server_create_result }}"
