# - debug:
#     var: subscription_id
- block:
  - name: create an empty array.
    set_fact:
      successed_uploads: []
  - name: upload one conf.
    include_tasks: upload-one-conf.yml
    loop: "{{ users_diff }}"
  - name: successed_uploads
    debug:
      msg: "{{ successed_uploads }}"
  vars:
    prefix: "{{'../configs' if in_test is defined else 'configs' }}/{{ vpn_server_ip }}/wireguard"
