# - debug:
#     var: subscription_id
- block:
  - name: caculate files by users.
    set_fact:
      o:
        - src: "{{ prefix }}/apple/ios/{{ item }}.mobileconfig"
          blob: "apple/ios/{{ item }}.mobileconfig"
        - src: "{{ prefix }}/apple/macos/{{ item }}.mobileconfig"
          blob: "apple/macos/{{ item }}.mobileconfig"
        - src: "{{ prefix }}/{{ item }}.conf"
          blob: "{{ item }}.conf"
        - src: "{{ prefix }}/{{ item }}.png"
          blob: "{{ item }}.png"
    loop: "{{ users }}"
    register: producted_items
  - name: print out producted_items
    debug:
      var: producted_items
  - name: set prepared blobs
    set_fact:
      prepared_blobs: 
  - name: upload conf.
    azure.azcollection.azure_rm_storageblob:
      resource_group: blob-resource-group
      storage_account_name: respme
      container: conf
      client_id: "{{uploader_sp_client_id}}"
      subscription_id: "{{subscription_id}}"
      tenant: jianglibohotmail.onmicrosoft.com
      secret: "{{uploader_sp_pwd}}"
      # ad_user: configs-uploader@jianglibohotmail.onmicrosoft.com
      # password: "{{ uploader_pwd }}"
      blob: "{{ item.blob }}"
      src: "{{ item.src }}"
      # auth_source: env
      # public_access: container
      # content_type: 'application/image'
    register: server_result
    loop: "{{ producted_items.results | map(attribute='ansible_facts.o') | flatten }}"
  - name: server result
    debug:
      msg: "{{ server_result }}"
  vars:
    prefix: "{{'../configs' if in_test is defined else 'configs' }}/{{ vpn_server_ip }}/wireguard"

# https://yaml-multiline.info/