---
- block:
  - name: Install the requirements
    pip:
      state: latest
      name:
        - pyOpenSSL
        - jinja2==2.8
        - segno
    tags:
      - always
      - skip_ansible_lint
  delegate_to: localhost
  become: false

- block:
  - name: Generate the SSH private key
    openssl_privatekey:
      path: "{{ SSH_keys.private }}"
      size: 2048
      mode: "0600"
      type: RSA

  - name: Generate the SSH public key
    openssl_publickey:
      path: "{{ SSH_keys.public }}"
      privatekey_path: "{{ SSH_keys.private }}"
      format: OpenSSH

  - name: Copy the private SSH key to /tmp
    copy:
      src: "{{ SSH_keys.private }}"
      dest: "{{ SSH_keys.private_tmp }}"
      force: true
      mode: '0600'
    delegate_to: localhost
    become: false
  when: algo_provider != "local"
