---
- hosts: localhost
  gather_facts: False
  tags: always
  vars_files:
    - ../vars/sec.yml
    - ../vars/cfg.yml
  tasks:
    - name: import tasks
      import_tasks: ../tasks/server-create-ql.yml
# ansible-playbook --vault-id hetzner@/opt/hetzner.pwd -e '{"vpn_server_ip": "2.2.2.2", "users": []}' subbooks/server-create-ql.yml -vv