---
- name: test shell
  hosts: localhost
  gather_facts: false
  vars:
    a: 12345
    arr: []
  tasks:
    - name: t shell
      shell: |
        echo '{{ a }}' &&
        echo 'hello{{ a }}'
      args:
        executable: /bin/bash
    - debug:
        msg: "{{ {'a': 1} | combine({'b': 2}) }}"
    - name: test array
      debug:
        msg: "{{ arr == [] }}"

- name: Configure the client
  hosts: localhost
  gather_facts: false
  become: false
  
  tasks:
    - name: Add the droplet to an inventory group
      add_host:
        name: "{{ client_ip }}"
        groups: vpn-server
        ansible_ssh_user: root

- name: Configure the client and install required software
  hosts: localhost
  # hosts: vpn-server
  gather_facts: false
  vars:
    list_var:
      - northeast
      - southeast
      - midwest
  tasks:
    - debug:
        var: client_ip
    - name: set list variables
      debug:
        msg: "{{ list_var | to_json }}"
    - name: Register loop output as a variable
      shell: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
    - debug:
        msg: "{{ echo.results | map(attribute='item') | list | to_json}}"
