---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config.cfg
    - ../vars/cfg.yml
  tasks:
    - name: test regex_replace
      # 288efec7-be65-4681-8b64-13741b0547fb
      debug:
        msg: "{{ ['288efec7be6546818b6413741b0547fb'] | map('regex_replace', '^(.{8})(.{4})(.{4})(.{4})', '\\1-\\2-\\3-\\4-') | list  }}"
      # when: ansible_facts.env.abc
    - name: fail if users not as expected.
      fail:
        msg: "just fail."
    - name: display file content
      debug:
        msg: "'{{ lookup('env', 'FC') }}' is the HOME environment variable."
    - name: can i override vars in config file?
      set_fact:
        users: ["ye"]
    - name: fail if users not as expected.
      fail:
        msg: "users is: {{ users }}"
      when: users != ["ye"]
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: iv.yml
        # name: stuff

    # - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      # include_vars: "{{ lookup('first_found', params) }}"
      # include_vars: "{{ lookup('file', 't-cfg.yml') }}"
      # vars:
      #   params:
      #     files:
      #       - '{{ansible_distribution}}.yaml'
      #       - '{{ansible_os_family}}.yaml'
      #       - default.yaml
      #     paths:
      #       - 'vars'
    - name: fail if users not as expected.
      fail:
        msg: "users is: {{ users }}"
      when: users != ["ye"]
    - debug:
        var: stuff
    - name: full template
      set_fact:
        v: |
          [
          {% for i in [['a', 1],['b', 2],['c', 3]] %}
            {"{{i.0}}": {{i.1}}},
          {% endfor %}]

    - name: use full tempalte
      debug:
        var: v[0].a1
    
    - name: saved port
      debug:
        var: saved_port_file
    - name: read unexists file.
      debug:
        msg: "{{lookup('file', '/etc/foo.taxt') }}"
      register: command_result
      ignore_errors: yes
    - name: error result
      debug:
        var: command_result

    - name: set default
      debug:
        msg: "{{ max_conf | default(250)}}"
    - name: Find out what the remote machine's mounts are
      slurp:
        src: i.txt
      register: mounts

    - debug:
        msg: "{{ mounts['content'] | b64decode }}"

# export FC=linoxide.com
  # ansible-playbook --vault-id hetzner@/opt/respme/hetzner.pwd subbooks/t-env.yml
