---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  tasks:
    - block:
      - name: some item failed.
        include_tasks: block-with-error.yml
        loop: "{{ numbers }}"
        ignore_errors: true
        # ignore_failed: true
        register: result
        # failed_when: "'xxxxx' in result.msg"
      - debug:
          var: result
      vars:
        numbers: [0,2,1,3]

# ansible-playbook --vault-id hetzner@/opt/respme/hetzner.pwd subbooks/t-ignore-errors.yml
