---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false

  tasks:
    - block:
      - name: Add a line to a file if the file does not exist, without passing regexp
        lineinfile:
          path: this_vpn_server_ip
          line: 192.168.1.99 foo.lab.net foo1
          create: yes
      - name: display file content
        debug:
          var: fc
      - name: remove file
        file:
          path: this_vpn_server_ip
          state: absent
      - name: string concat
        debug:
          msg: "{{ respme_base + '/this_vpn_server_ip' }}"
      - name: test key in dict.
        debug:
          msg: "a.b not in: {{ 'a.b' in {'a': {'b': 1}} }}, but a in: {{ 'a' in {'a': {'b': 1}} }}, {{ {'a': {'b': 1}}['a'] }}"

      vars:
        respme_base: "abc"
        fc: "{{ lookup('file', rempme_base + '/this_vpn_server_ip') }}"

  # ansible-playbook --vault-id hetzner@/opt/respme/hetzner.pwd subbooks/t-lineinfile.yml
