---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  tasks:
    - block:
      - debug:
          var: users_list
      - name: write users to file.
        copy:
          content: "{{ users_list }}"
          dest: users_list.json
      vars:
        users_list: "{{ [{'id': 1}, {'id': 2}] | map(attribute='id') | map('regex_replace', '^(.*)$', 's-\\1') | list }}" 

# export FC=linoxide.com
  # ansible-playbook --vault-id hetzner@/opt/hetzner.pwd subbooks/t-map.yml
