---
- name: Configure the server and install required software
  hosts: localhost
  gather_facts: false
  tasks:
    - block:
      - name: difference object value
        debug:
          msg: "{{ 'abc'| a_filter }}"

# ansible-playbook --vault-id hetzner@/opt/hetzner.pwd subbooks/t-my-filter.yml
