---
- hosts: localhost
  gather_facts: false
  tags: always
  vars_files:
    - ../vars/sec.yml
    - ../vars/cfg.yml
  # environment:
  #   AZURE_AD_USER: configs-uploader@jianglibohotmail.onmicrosoft.com
  #   AZURE_PASSWORD: "{{ uploader_pwd }}"
  tasks:
    - name: import tasks
      import_tasks: ../tasks/update-conf-users.yml
      vars:
        successed_uploads: ["6f5f4e42-05ff-4225-9d3e-4132121542ff"]

# ansible-playbook --vault-id hetzner@/opt/respme/hetzner.pwd -e '{"in_test": true}' subbooks/t-update-conf-users.yml